CREATE DATABASE IF NOT EXISTS vuno_app_leeds
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE vuno_app_leeds;

CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  whatsapp_apikey VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tiers (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  created_by CHAR(36) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS products (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  base_price DECIMAL(10,2) DEFAULT NULL,
  created_by CHAR(36) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS templates (
  id CHAR(36) PRIMARY KEY,
  template_name VARCHAR(255) NOT NULL,
  message_body TEXT NOT NULL,
  product_id CHAR(36) DEFAULT NULL,
  created_by CHAR(36) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS categories (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  created_by CHAR(36) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS leads (
  id CHAR(36) PRIMARY KEY,
  store_name VARCHAR(255) NOT NULL,
  profile_url VARCHAR(500) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(255) DEFAULT NULL,
  followers_count INT DEFAULT 0,
  tier_classification VARCHAR(50) DEFAULT NULL,
  product_id CHAR(36) DEFAULT NULL,
  category_id CHAR(36) DEFAULT NULL,
  contact_status ENUM('Pending', 'First Contact', 'Second Contact', 'Interested', 'Client', 'Archived') NOT NULL DEFAULT 'Pending',
  contact_attempts INT NOT NULL DEFAULT 0,
  last_contact_date DATETIME DEFAULT NULL,
  created_by CHAR(36) NOT NULL,
  registration_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY uq_phone_profile (phone, profile_url),
  INDEX idx_follow_up (contact_status, last_contact_date)
) ENGINE=InnoDB;

INSERT INTO users (id, email, password, created_at) VALUES
  ('018e7c40-0000-7000-8000-000000000001', 'dail', '$2y$10$kyuPfiPWb9iKduUb15wPL.ReNE7KZpkkB8SPGIRCgE4tufa7CfXX.', NOW())
ON DUPLICATE KEY UPDATE email = email;

INSERT INTO tiers (id, name, price, created_by) VALUES
  ('01900001-0000-7000-8000-000000000001', 'Tier 1', 50.00, '018e7c40-0000-7000-8000-000000000001'),
  ('01900001-0000-7000-8000-000000000002', 'Tier 2', 100.00, '018e7c40-0000-7000-8000-000000000001'),
  ('01900001-0000-7000-8000-000000000003', 'Tier 3', 200.00, '018e7c40-0000-7000-8000-000000000001')
ON DUPLICATE KEY UPDATE name = name;
